#
# SOC-Analyst app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 1
label = SOC-Analyst

[launcher]
author = SOC-Analyst Team
description = SOC Analyst toolbox for Splunk: threat hunting, monitoring and investigations.
version = 1.0

[package]
id = soc-analyst-splunk-app
check_for_updates = 0