[threat_intel_hashes]
external_type = csv
filename = threat_intel_hashes.csv

[asset_inventory]
external_type = csv
filename = asset_inventory.csv

[user_identity]
external_type = csv
filename = user_identity.csv

[threat_intel_ips]
external_type = csv
filename = threat_intel_ips.csv

[threat_intel_domains]
external_type = csv
filename = threat_intel_domains.csv
