[soc_analyst]
definition = index=*

[soc_endpoint]
definition = sourcetype="WinEventLog:Sysmon" OR sourcetype="xmlwineventlog"

[soc_auth]
definition = sourcetype="WinEventLog:Security" index=windows_security
iseval = 0

[soc_network]
definition = index=netflow OR index=proxy OR index=firewall