[incident - sample search]
disabled = 0
search = `soc_analyst` | stats count by index
cron_schedule = 0 * * * *
earliest_time = -24h@h
latest_time = now
description = Example saved search for the SOC-Analyst app
is_scheduled = 1